site :opscode

metadata

cookbook 'libzmq', github: 'ProjectMeniscus/chef-libzmq'
cookbook 'syslogng-transport', path: '../syslogng-transport'

cookbook 'authorized_keys', github: 'ProjectMeniscus/authorized_keys'
cookbook 'cloudpassage', github: 'ProjectMeniscus/chef-cloudpassage'
cookbook 'newrelic', github: 'escapestudios/chef-newrelic'
cookbook 'base-template', path: '../base-template'