site :opscode

metadata

cookbook 'apt'
cookbook 'syslogng-transport', path: '../syslogng-transport'
cookbook 'hayrack', path: '../hayrack'

cookbook 'authorized_keys', github: 'ProjectMeniscus/authorized_keys'
cookbook 'cloudpassage', github: 'ProjectMeniscus/chef-cloudpassage'
cookbook 'newrelic', github: 'escapestudios/chef-newrelic'
cookbook 'base-template', path: '../base-template'