site :opscode

metadata

cookbook 'authorized_keys', github: 'ProjectMeniscus/authorized_keys'
cookbook 'cloudpassage', github: 'ProjectMeniscus/chef-cloudpassage'
cookbook 'newrelic', github: 'escapestudios/chef-newrelic'

cookbook 'base-template', path: '../base-template'
cookbook 'mmongo', path: '../mmongo'
cookbook 'meetme-newrelic-plugin', git: 'git@github.com:ProjectMeniscus/chef-meetme-newrelic-plugin'