metadata

cookbook 'apt', git: 'git://github.com/opscode-cookbooks/apt.git'
cookbook 'java', git: 'git://github.com/opscode-cookbooks/java.git'
cookbook 'elasticsearch', git: 'git@github.com:ProjectMeniscus/cookbook-elasticsearch.git'


