site :opscode

metadata

cookbook 'authorized_keys', github: 'ProjectMeniscus/authorized_keys'
cookbook 'cloudpassage', github: 'ProjectMeniscus/chef-cloudpassage'
cookbook 'newrelic', github: 'escapestudios/chef-newrelic'

cookbook 'base-template', path: '../base-template'

cookbook 'liblognorm', github: 'ProjectMeniscus/chef-liblognorm'
cookbook 'libzmq', github: 'ProjectMeniscus/chef-libzmq'
cookbook 'meetme-newrelic-plugin', github: 'ProjectMeniscus/chef-meetme-newrelic-plugin'


cookbook 'meniscus', path: '../meniscus'