# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  # -*- mode: ruby -*-
# vi: set ft=ruby :
  config.vm.box = "precise64"
  config.vm.box_url = "http://acc22a19bc318afc0ac4-2cdbfc3810207176667868d343dae57a.r98.cf2.rackcdn.com/vbox4.3.2-ruby1.9.3-chef11.6-precise64.box"
  config.vm.hostname = "kibana-berkshelf"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "https://dl.dropbox.com/u/31081437/Berkshelf-CentOS-6.3-x86_64-minimal.box"

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :private_network, ip: "33.33.33.10"

  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.json = {
      :kibana => {
        :proxy_server => "localhost",
        :keystone_server => "localhost",
      }
    }

    chef.run_list = [
        "recipe[kibana::default]"
    ]
  end
end
